; Auto-generated. Do not edit!


(cl:in-package cuboat_actuators-msg)


;//! \htmlinclude servoResult.msg.html

(cl:defclass <servoResult> (roslisp-msg-protocol:ros-message)
  ((finish
    :reader finish
    :initarg :finish
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass servoResult (<servoResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <servoResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'servoResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cuboat_actuators-msg:<servoResult> is deprecated: use cuboat_actuators-msg:servoResult instead.")))

(cl:ensure-generic-function 'finish-val :lambda-list '(m))
(cl:defmethod finish-val ((m <servoResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cuboat_actuators-msg:finish-val is deprecated.  Use cuboat_actuators-msg:finish instead.")
  (finish m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <servoResult>) ostream)
  "Serializes a message object of type '<servoResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'finish) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <servoResult>) istream)
  "Deserializes a message object of type '<servoResult>"
    (cl:setf (cl:slot-value msg 'finish) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<servoResult>)))
  "Returns string type for a message object of type '<servoResult>"
  "cuboat_actuators/servoResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'servoResult)))
  "Returns string type for a message object of type 'servoResult"
  "cuboat_actuators/servoResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<servoResult>)))
  "Returns md5sum for a message object of type '<servoResult>"
  "474a58dbb494a45bb1ca99544cd64e45")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'servoResult)))
  "Returns md5sum for a message object of type 'servoResult"
  "474a58dbb494a45bb1ca99544cd64e45")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<servoResult>)))
  "Returns full string definition for message of type '<servoResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#part2: the result message, to be sent by the server upon completion~%bool finish~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'servoResult)))
  "Returns full string definition for message of type 'servoResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#part2: the result message, to be sent by the server upon completion~%bool finish~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <servoResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <servoResult>))
  "Converts a ROS message object to a list"
  (cl:list 'servoResult
    (cl:cons ':finish (finish msg))
))
