// Generated by gencpp from file pid_control_pkg/pid_target.msg
// DO NOT EDIT!


#ifndef PID_CONTROL_PKG_MESSAGE_PID_TARGET_H
#define PID_CONTROL_PKG_MESSAGE_PID_TARGET_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pid_control_pkg
{
template <class ContainerAllocator>
struct pid_target_
{
  typedef pid_target_<ContainerAllocator> Type;

  pid_target_()
    : x(0.0)
    , y(0.0)
    , yaw(0.0)  {
    }
  pid_target_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::pid_control_pkg::pid_target_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pid_control_pkg::pid_target_<ContainerAllocator> const> ConstPtr;

}; // struct pid_target_

typedef ::pid_control_pkg::pid_target_<std::allocator<void> > pid_target;

typedef boost::shared_ptr< ::pid_control_pkg::pid_target > pid_targetPtr;
typedef boost::shared_ptr< ::pid_control_pkg::pid_target const> pid_targetConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pid_control_pkg::pid_target_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pid_control_pkg::pid_target_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pid_control_pkg::pid_target_<ContainerAllocator1> & lhs, const ::pid_control_pkg::pid_target_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pid_control_pkg::pid_target_<ContainerAllocator1> & lhs, const ::pid_control_pkg::pid_target_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pid_control_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pid_control_pkg::pid_target_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pid_control_pkg::pid_target_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pid_control_pkg::pid_target_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pid_control_pkg::pid_target_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pid_control_pkg::pid_target_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pid_control_pkg::pid_target_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pid_control_pkg::pid_target_<ContainerAllocator> >
{
  static const char* value()
  {
    return "47802147045815b06859cca542c21d31";
  }

  static const char* value(const ::pid_control_pkg::pid_target_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x47802147045815b0ULL;
  static const uint64_t static_value2 = 0x6859cca542c21d31ULL;
};

template<class ContainerAllocator>
struct DataType< ::pid_control_pkg::pid_target_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pid_control_pkg/pid_target";
  }

  static const char* value(const ::pid_control_pkg::pid_target_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pid_control_pkg::pid_target_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 yaw\n"
;
  }

  static const char* value(const ::pid_control_pkg::pid_target_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pid_control_pkg::pid_target_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pid_target_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pid_control_pkg::pid_target_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pid_control_pkg::pid_target_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PID_CONTROL_PKG_MESSAGE_PID_TARGET_H
