// Generated by gencpp from file cuboat_actuators/propeller.msg
// DO NOT EDIT!


#ifndef CUBOAT_ACTUATORS_MESSAGE_PROPELLER_H
#define CUBOAT_ACTUATORS_MESSAGE_PROPELLER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cuboat_actuators
{
template <class ContainerAllocator>
struct propeller_
{
  typedef propeller_<ContainerAllocator> Type;

  propeller_()
    : front(0)
    , back(0)
    , left(0)
    , right(0)  {
    }
  propeller_(const ContainerAllocator& _alloc)
    : front(0)
    , back(0)
    , left(0)
    , right(0)  {
  (void)_alloc;
    }



   typedef uint16_t _front_type;
  _front_type front;

   typedef uint16_t _back_type;
  _back_type back;

   typedef uint16_t _left_type;
  _left_type left;

   typedef uint16_t _right_type;
  _right_type right;





  typedef boost::shared_ptr< ::cuboat_actuators::propeller_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cuboat_actuators::propeller_<ContainerAllocator> const> ConstPtr;

}; // struct propeller_

typedef ::cuboat_actuators::propeller_<std::allocator<void> > propeller;

typedef boost::shared_ptr< ::cuboat_actuators::propeller > propellerPtr;
typedef boost::shared_ptr< ::cuboat_actuators::propeller const> propellerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cuboat_actuators::propeller_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cuboat_actuators::propeller_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cuboat_actuators::propeller_<ContainerAllocator1> & lhs, const ::cuboat_actuators::propeller_<ContainerAllocator2> & rhs)
{
  return lhs.front == rhs.front &&
    lhs.back == rhs.back &&
    lhs.left == rhs.left &&
    lhs.right == rhs.right;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cuboat_actuators::propeller_<ContainerAllocator1> & lhs, const ::cuboat_actuators::propeller_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cuboat_actuators

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cuboat_actuators::propeller_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cuboat_actuators::propeller_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cuboat_actuators::propeller_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cuboat_actuators::propeller_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cuboat_actuators::propeller_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cuboat_actuators::propeller_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cuboat_actuators::propeller_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6a6f565cf70a0be5a8e5d7b7cab7b826";
  }

  static const char* value(const ::cuboat_actuators::propeller_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6a6f565cf70a0be5ULL;
  static const uint64_t static_value2 = 0xa8e5d7b7cab7b826ULL;
};

template<class ContainerAllocator>
struct DataType< ::cuboat_actuators::propeller_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cuboat_actuators/propeller";
  }

  static const char* value(const ::cuboat_actuators::propeller_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cuboat_actuators::propeller_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 front\n"
"uint16 back\n"
"uint16 left\n"
"uint16 right\n"
;
  }

  static const char* value(const ::cuboat_actuators::propeller_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cuboat_actuators::propeller_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.front);
      stream.next(m.back);
      stream.next(m.left);
      stream.next(m.right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct propeller_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cuboat_actuators::propeller_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cuboat_actuators::propeller_<ContainerAllocator>& v)
  {
    s << indent << "front: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.front);
    s << indent << "back: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.back);
    s << indent << "left: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUBOAT_ACTUATORS_MESSAGE_PROPELLER_H
