// Generated by gencpp from file cuboat_actuators/servoResult.msg
// DO NOT EDIT!


#ifndef CUBOAT_ACTUATORS_MESSAGE_SERVORESULT_H
#define CUBOAT_ACTUATORS_MESSAGE_SERVORESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cuboat_actuators
{
template <class ContainerAllocator>
struct servoResult_
{
  typedef servoResult_<ContainerAllocator> Type;

  servoResult_()
    : finish(false)  {
    }
  servoResult_(const ContainerAllocator& _alloc)
    : finish(false)  {
  (void)_alloc;
    }



   typedef uint8_t _finish_type;
  _finish_type finish;





  typedef boost::shared_ptr< ::cuboat_actuators::servoResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cuboat_actuators::servoResult_<ContainerAllocator> const> ConstPtr;

}; // struct servoResult_

typedef ::cuboat_actuators::servoResult_<std::allocator<void> > servoResult;

typedef boost::shared_ptr< ::cuboat_actuators::servoResult > servoResultPtr;
typedef boost::shared_ptr< ::cuboat_actuators::servoResult const> servoResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cuboat_actuators::servoResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cuboat_actuators::servoResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cuboat_actuators::servoResult_<ContainerAllocator1> & lhs, const ::cuboat_actuators::servoResult_<ContainerAllocator2> & rhs)
{
  return lhs.finish == rhs.finish;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cuboat_actuators::servoResult_<ContainerAllocator1> & lhs, const ::cuboat_actuators::servoResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cuboat_actuators

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cuboat_actuators::servoResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cuboat_actuators::servoResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cuboat_actuators::servoResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cuboat_actuators::servoResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cuboat_actuators::servoResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cuboat_actuators::servoResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cuboat_actuators::servoResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "474a58dbb494a45bb1ca99544cd64e45";
  }

  static const char* value(const ::cuboat_actuators::servoResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x474a58dbb494a45bULL;
  static const uint64_t static_value2 = 0xb1ca99544cd64e45ULL;
};

template<class ContainerAllocator>
struct DataType< ::cuboat_actuators::servoResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cuboat_actuators/servoResult";
  }

  static const char* value(const ::cuboat_actuators::servoResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cuboat_actuators::servoResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#part2: the result message, to be sent by the server upon completion\n"
"bool finish\n"
;
  }

  static const char* value(const ::cuboat_actuators::servoResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cuboat_actuators::servoResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.finish);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct servoResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cuboat_actuators::servoResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cuboat_actuators::servoResult_<ContainerAllocator>& v)
  {
    s << indent << "finish: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.finish);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUBOAT_ACTUATORS_MESSAGE_SERVORESULT_H
