; Auto-generated. Do not edit!


(cl:in-package cuboat_actuators-msg)


;//! \htmlinclude servoGoal.msg.html

(cl:defclass <servoGoal> (roslisp-msg-protocol:ros-message)
  ((index
    :reader index
    :initarg :index
    :type cl:fixnum
    :initform 0)
   (state
    :reader state
    :initarg :state
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass servoGoal (<servoGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <servoGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'servoGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cuboat_actuators-msg:<servoGoal> is deprecated: use cuboat_actuators-msg:servoGoal instead.")))

(cl:ensure-generic-function 'index-val :lambda-list '(m))
(cl:defmethod index-val ((m <servoGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cuboat_actuators-msg:index-val is deprecated.  Use cuboat_actuators-msg:index instead.")
  (index m))

(cl:ensure-generic-function 'state-val :lambda-list '(m))
(cl:defmethod state-val ((m <servoGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cuboat_actuators-msg:state-val is deprecated.  Use cuboat_actuators-msg:state instead.")
  (state m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <servoGoal>) ostream)
  "Serializes a message object of type '<servoGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'index)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'state) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <servoGoal>) istream)
  "Deserializes a message object of type '<servoGoal>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'index)) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'state) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<servoGoal>)))
  "Returns string type for a message object of type '<servoGoal>"
  "cuboat_actuators/servoGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'servoGoal)))
  "Returns string type for a message object of type 'servoGoal"
  "cuboat_actuators/servoGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<servoGoal>)))
  "Returns md5sum for a message object of type '<servoGoal>"
  "56a80a4bb2c205f050ad25bcdcdc1b1f")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'servoGoal)))
  "Returns md5sum for a message object of type 'servoGoal"
  "56a80a4bb2c205f050ad25bcdcdc1b1f")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<servoGoal>)))
  "Returns full string definition for message of type '<servoGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#part1: the goal message, to be sent by the client~%uint8 index~%bool state~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'servoGoal)))
  "Returns full string definition for message of type 'servoGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#part1: the goal message, to be sent by the client~%uint8 index~%bool state~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <servoGoal>))
  (cl:+ 0
     1
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <servoGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'servoGoal
    (cl:cons ':index (index msg))
    (cl:cons ':state (state msg))
))
