; Auto-generated. Do not edit!


(cl:in-package cuboat_actuators-msg)


;//! \htmlinclude servoFeedback.msg.html

(cl:defclass <servoFeedback> (roslisp-msg-protocol:ros-message)
  ((complete_percentage
    :reader complete_percentage
    :initarg :complete_percentage
    :type cl:float
    :initform 0.0))
)

(cl:defclass servoFeedback (<servoFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <servoFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'servoFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cuboat_actuators-msg:<servoFeedback> is deprecated: use cuboat_actuators-msg:servoFeedback instead.")))

(cl:ensure-generic-function 'complete_percentage-val :lambda-list '(m))
(cl:defmethod complete_percentage-val ((m <servoFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cuboat_actuators-msg:complete_percentage-val is deprecated.  Use cuboat_actuators-msg:complete_percentage instead.")
  (complete_percentage m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <servoFeedback>) ostream)
  "Serializes a message object of type '<servoFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'complete_percentage))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <servoFeedback>) istream)
  "Deserializes a message object of type '<servoFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'complete_percentage) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<servoFeedback>)))
  "Returns string type for a message object of type '<servoFeedback>"
  "cuboat_actuators/servoFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'servoFeedback)))
  "Returns string type for a message object of type 'servoFeedback"
  "cuboat_actuators/servoFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<servoFeedback>)))
  "Returns md5sum for a message object of type '<servoFeedback>"
  "756c384977ae119574d7b7f885f900d9")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'servoFeedback)))
  "Returns md5sum for a message object of type 'servoFeedback"
  "756c384977ae119574d7b7f885f900d9")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<servoFeedback>)))
  "Returns full string definition for message of type '<servoFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#part3: the feedback message, to be sent by server during execution~%float32 complete_percentage~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'servoFeedback)))
  "Returns full string definition for message of type 'servoFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#part3: the feedback message, to be sent by server during execution~%float32 complete_percentage~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <servoFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <servoFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'servoFeedback
    (cl:cons ':complete_percentage (complete_percentage msg))
))
